fastlane_version "1.17.1"
default_platform :ios
platform :ios do

  lane :prebuild do
    cocoapods
  end

  lane :postbuild do
    # slack(
    #   message: "Xcode Bot reporting success."
    # )
    say "Xcode Bot reporting success."
  end
  
end
